FROM rust:1.90-alpine AS builder

WORKDIR /app

RUN apk add --no-cache musl-dev

COPY Cargo.toml Cargo.lock ./
COPY src ./src

RUN cargo build

RUN cargo install cargo-watch

CMD ["cargo", "watch", "-x", "run"]
