FROM bellsoft/liberica-openjdk-alpine-musl:21

WORKDIR /app

RUN apk add --no-cache bash curl unzip

COPY mvnw pom.xml ./
COPY .mvn .mvn

RUN chmod +x mvnw \
    && ./mvnw -B dependency:go-offline

COPY src ./src

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run"]
