from typing import Any

class DockerClient:
    @classmethod
    def from_env(cls, **kwargs: Any) -> "DockerClient": ...
    def ping(self) -> None: ...
    def close(self) -> None: ...

def from_env(**kwargs: Any) -> DockerClient: ...

__all__ = ["DockerClient", "from_env"]
