from typing import Any

class MySqlContainer:
    def __init__(self, image: str = ..., **kwargs: Any) -> None: ...
    def __enter__(self) -> MySqlContainer: ...
    def __exit__(self, exc_type: type | None, exc: Exception | None, tb: Any | None) -> None: ...
    def start(self) -> MySqlContainer: ...
    def stop(self) -> None: ...
    def get_connection_url(self) -> str: ...
